/* Civic Signal Atlas: problem-statement-first briefing room for MPLADS anomaly review. */
import { useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, CircleAlert, Database, FileSearch, GitBranch, MapPin, Radar, ShieldCheck, SlidersHorizontal, TimerReset } from 'lucide-react';
import { Hero7Carousel, Hero9Reveal, ScrollExpand, TargetCursor } from '@/components/SignalExperiences';

const riskRows = [
  ['DEMO / MH-2024-1187', 'Nashik · Water infrastructure', 'Data inconsistency', '87', 'Text + geo'],
  ['DEMO / RJ-2024-0412', 'Kota · Rural road', 'Completion mismatch', '76', 'Utilization'],
  ['DEMO / KA-2023-0920', 'Mysuru · Sanitation', 'Agency concentration', '63', 'Graph signal'],
];

const detectionEngines = [
  { number: '01', title: 'Financial anomalies', copy: 'Benford deviation, cost-versus-category baselines, utilization mismatch, and multivariate outliers.', icon: SlidersHorizontal },
  { number: '02', title: 'Duplicate / ghost works', copy: 'Description similarity plus district, constituency, category, location, and cost clustering.', icon: FileSearch },
  { number: '03', title: 'Delay and SLA breach', copy: 'Days since sanction, category-aware completion benchmarks, and chronic-delay agency patterns.', icon: TimerReset },
  { number: '04', title: 'Compliance and network', copy: 'Eligibility rules, SC/ST allocation checks, and District Authority → Agency → Vendor concentration.', icon: GitBranch },
];

const workflow = [
  ['01', 'Recommend', 'MP recommends an eligible community asset through eSAKSHI.'],
  ['02', 'Sanction', 'District Authority checks feasibility, cost, and guideline compliance.'],
  ['03', 'Execute', 'Implementing Agency updates progress and vendor payments.'],
  ['04', 'Review', 'Sentinel compares the record and explains what needs verification.'],
];

export default function Home() {
  const [activeTab, setActiveTab] = useState<'public' | 'investigator'>('public');
  return <div className="site-shell"><TargetCursor />
    <header className="site-header"><a href="#top" className="wordmark cursor-target"><img src="/manus-storage/mplad-sentinel-mark_5650636e.png" alt="" /><span><b>MPLAD</b><small>SENTINEL</small></span></a><nav><a href="#how-it-works" className="cursor-target">How it works</a><a href="#signals" className="cursor-target">Signals</a><a href="#method" className="cursor-target">Method</a></nav><a href="#investigate" className="header-action cursor-target">Open investigator view <ArrowUpRight size={15} /></a></header>
    <main id="top">
      <section className="hero-shell"><Hero9Reveal /><div className="hero7-panel"><div className="panel-kicker"><span>02 / SIGNAL FIELD</span><span>FY 2023–24 →</span></div><Hero7Carousel /></div><div className="hero-side-note"><span className="vertical-label">CIVIC INTELLIGENCE / PUBLIC WORKS</span><span className="scroll-mark">01 — 04</span></div></section>

      <section className="briefing-intro" id="how-it-works"><div className="section-index">01 <span>THE ACTUAL GAP</span></div><div className="intro-copy"><div className="source-stamp">SIH26102 / MPLADS INTELLIGENCE LAYER</div><h1>eSAKSHI records what happened. <em>Sentinel checks what needs a second look.</em></h1><p>MPLADS already has a digital workflow for recommendations, sanctions, execution updates, payments, and completed works. The problem statement asks for the missing detection layer: a system that compares those records across time, place, category, cost, and implementing network to surface review-recommended inconsistencies.</p><div className="briefing-links"><a className="text-link cursor-target" href="#flow">Trace the scheme workflow <ArrowDownRight size={17} /></a><a className="source-inline cursor-target" href="https://www.mospi.gov.in/about-us/mplads" target="_blank" rel="noreferrer">MoSPI source <ArrowUpRight size={13} /></a></div></div><div className="intro-aside"><div className="metric-big">₹5<span>crore / MP / year<br />scheme entitlement stated in brief</span></div><p>Non-lapsable funds are recommended by MPs, sanctioned by District Authorities, and executed by Implementing Agencies. The product must not collapse those roles into a single accusation.</p></div></section>

      <section className="flow-section" id="flow"><div className="field-rail">ROLE SEPARATION / 01</div><div className="section-heading"><div><span className="eyebrow">01 / WHO DOES WHAT</span><h2>Follow the money<br /><em>without blaming the wrong actor.</em></h2></div><p>The brief is explicit about responsibility: recommendation, sanction, execution, and payment are different stages with different evidence.</p></div><div className="workflow-grid">{workflow.map(([number, title, copy]) => <div className="workflow-step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div><ChevronRight size={16} /></div>)}</div><div className="data-boundary"><CircleAlert size={17} /><div><strong>Coverage boundary</strong><p>eSAKSHI became effective from 1 April 2023. Pre-2023 work-level detail is not uniformly available because the scheme was implemented through physical district records. Sentinel must display this limitation instead of presenting an apparently complete historical series.</p></div></div></section>

      <section className="signal-section" id="signals"><div className="field-rail">FIELD NOTE 02 / REVIEW QUEUE</div><div className="section-heading"><div><span className="eyebrow">02 / DETECTION OUTPUT</span><h2>Where records<br /><em>stop agreeing.</em></h2></div><p>These are illustrative demo rows, not real accusations or live scheme results. A production queue must be backed by verified data and human review.</p></div><div className="risk-table-wrap"><div className="table-top"><span><Radar size={16} /> ILLUSTRATIVE REVIEW QUEUE</span><span>3 DEMO CANDIDATES <i>●</i></span></div><div className="risk-table">{riskRows.map((r) => <div className="risk-row" key={r[0]}><span className="risk-id">{r[0]}</span><span className="risk-project">{r[1]}</span><span className="risk-type">{r[2]}</span><span className={`risk-score score-${r[3]}`}>{r[3]}</span><span className="risk-method">{r[4]}</span><button className="row-arrow cursor-target" aria-label={`Open illustrative case ${r[0]}`}><ChevronRight size={17} /></button></div>)}</div><div className="table-bottom"><span>Illustrative rows only · no live API connected</span><a href="#investigate" className="cursor-target">See the two views <ArrowUpRight size={14} /></a></div></div></section>

      <section className="evidence-section"><div className="evidence-stamp">SOURCE TRACE / 03</div><ScrollExpand><img src="/manus-storage/mplad-investigation_3b4bbb25.jpg" alt="Abstract evidence desk representing project records, documents, and source traces" /><div className="evidence-overlay"><span className="evidence-frame-mark">[ WHY THIS FLAG EXISTS ]</span><span className="eyebrow">EXPLAINABILITY IS THE PRODUCT</span><h2>A score without a reason<br /><em>cannot survive review.</em></h2><p>Every candidate should show the exact signal that fired: cost versus comparable works, similarity to another project, days since sanction, compliance breach, or agency-network concentration. The number is secondary to the evidence trail.</p></div></ScrollExpand></section>

      <section className="method-section" id="method"><div className="section-index">03 <span>THE DETECTION ENGINE</span></div><div className="method-grid"><div className="method-lead"><h2>Five weighted checks.<br /><em>One reviewable score.</em></h2><p>The proposed 0–100 composite is intentionally auditable: financial 30%, duplicate/ghost 25%, delay 20%, compliance 15%, and vendor/agency graph 10%.</p><a href="#investigate" className="button-coral cursor-target">See how a case is explained <ArrowUpRight size={16} /></a></div>{detectionEngines.map(({ number, title, copy, icon: Icon }) => <div className="method-card" key={number}><span>{number}</span><div className="method-icon"><Icon size={20} /></div><h3>{title}</h3><p>{copy}</p></div>)}</div><div className="score-ledger"><div><strong>30%</strong><span>Financial</span></div><div><strong>25%</strong><span>Duplicate / ghost</span></div><div><strong>20%</strong><span>Delay</span></div><div><strong>15%</strong><span>Compliance</span></div><div><strong>10%</strong><span>Agency graph</span></div></div></section>

      <section className="investigator-section" id="investigate"><div className="investigator-visual"><img src="/manus-storage/mplad-district-texture_d6fee9ee.jpg" alt="Abstract district map texture" /><div className="map-spot spot-a" /><div className="map-spot spot-b" /><div className="map-spot spot-c" /><div className="map-legend"><span className="legend-dot" /> aggregate signal · not a verdict</div></div><div className="investigator-copy"><span className="eyebrow">04 / TWO AUDIENCES, ONE BACKBONE</span><h2>Make transparency<br /><em>actionable.</em></h2><p>Public users need safe aggregate patterns. Investigators need the reason breakdown, similar-project links, vendor graph, case status, notes, and export trail. Same data backbone; different access and language.</p><div className="tabs"><button className={`cursor-target ${activeTab === 'public' ? 'active' : ''}`} onClick={() => setActiveTab('public')}>Public view <ChevronRight size={14} /></button><button className={`cursor-target ${activeTab === 'investigator' ? 'active' : ''}`} onClick={() => setActiveTab('investigator')}>Investigator view <ChevronRight size={14} /></button></div><div className="mode-note"><CircleAlert size={16} /><span>{activeTab === 'public' ? 'Shows aggregate utilization, completion, and review-recommended patterns without naming individuals as corrupt.' : 'Shows a ranked queue, reason strings, similar projects, agency relationships, case labels, notes, and PDF/CSV export.'}</span></div></div></section>

      <section className="source-section"><div className="section-index">05 <span>BUILD ON REAL EVIDENCE</span></div><div className="source-grid"><div><h2>Start with the sources<br /><em>judges will ask about.</em></h2><p>For a credible prototype, use the real eSAKSHI public dashboard and structured data.gov.in/Dataful exports as the backbone, PIB releases to validate pending-work patterns, and CAG reports as historical audit references. Clearly label any synthetic injections used to demonstrate detection.</p></div><div className="source-list"><a href="https://mplads.mospi.gov.in/" target="_blank" rel="noreferrer"><Database size={16} /> eSAKSHI / MoSPI <ArrowUpRight size={13} /></a><a href="https://www.data.gov.in/" target="_blank" rel="noreferrer"><MapPin size={16} /> data.gov.in / Dataful <ArrowUpRight size={13} /></a><a href="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2235932" target="_blank" rel="noreferrer"><Check size={16} /> PIB dashboard release <ArrowUpRight size={13} /></a><a href="https://cag.gov.in/en/audit-report/details/2341" target="_blank" rel="noreferrer"><ShieldCheck size={16} /> CAG audit reference <ArrowUpRight size={13} /></a></div></div></section>
    </main><footer className="site-footer"><span>© 2026 MPLAD SENTINEL / PROPOSED SIH26102 SOLUTION</span><span>REVIEW-RECOMMENDED / NOT ACCUSATION</span><a href="#top" className="cursor-target">Back to top <ArrowUpRight size={13} /></a></footer>
  </div>;
}
